### ISSUE TITLE
Creating github.io page

### ISSUE THREAD

**Issue by alexseguin** [AES-Outreach/SwaggerGen#58]
## Description
We need to create a nice web page to display our product on that would also support embedding our test generated endpoints. 

I suggest looking at the websites created  by other open source solutions that are widely used for inspiration.

## Tasks
- [ ] Create modern web page for SwaggerGen, incorporating the logo
- [ ] Content should include readme info, but also include more details (this page is *customer facing*)
- [ ] Integration of our generated sample swagger HTML files using Travis (a script would do the trick)

Feel free to ask for help if needed

**Comment by GuillaumeC91** [comment]
There is, of course, plenty of options but here are some simple (and free) Bootstrap 4 templates to choose from: https://startbootstrap.com/themes/

**Comment by flopmeister** [comment]
On it fellas.
